FROM tcp-over-websocket-base:latest

# Copy client 1 configuration
COPY test_config/websocket_client_1/config.json /root/tcp-over-websocket.home/

# Expose client ports for both tunnels
EXPOSE 38011 38012

CMD ["run_tcp_over_websocket_service", "/root/tcp-over-websocket.home"]